language: node_js
version: "6"
deploy:
    provider: s3
    access_key_id: ${S3_ACCESS_KEY_ID}
    secret_access_key: ${S3_SECRET_KEY}
    upload-dir: blueprints
    acl: public_read
    bucket: "alxdark.com"
    skip_cleanup: true
    region: "us-west-2"
