function f() {
    return [].slice.call(arguments).reduce(function(object, value) {
        var key = value.replace(/\s&\s/,"_").replace(/[\s-]/g,"_").replace(/'/,'').toLowerCase();
        object[key] = window[key] = value;
        return object;
    }, {});
}
var c = f("App", "Article", "Boycott", "Calendar", "Campaign", "Corruption", "Event", "Mailing List", "News", 
    "Organization", "Person", "Podcast", "Resource", "Racial Justice", "Civil Rights", "Civil Society", 
    "Community Organizing", "Congress", "Economic Justice", "Elections", "Environment", "GOP", "Gun Violence", 
    "Healthcare", "Homelessness", "Immigration & Refugees", "LGBTQ", "Media", "News", "Prison Reform", "Privacy", 
    "Regionalism", "Religious Freedom", "Science", "Security", "Self-Care", "Strategy", "Technology", "Trump", 
    "Video", "Voting Rights", "Washington State", "Weeklies", "Women's Rights");
var t = f("App", "Article", "Boycott", "Calendar", "Campaign", "Event", "Mailing List", "News", 
    "Organization", "Person", "Podcast", "Press Release", "Resource", "Video");

var data = [
 {title: "#GrabYourWallet", url: "https://grabyourwallet.org/", cat: [boycott], info: "Boycott of Trump products started after tapes of him bragging of sexual assault surfaced. "}
,{title: "#KnockEveryDoor", url: "https://knockeverydoor.org/", cat: [organization, elections], info: "Nationwide, volunteer-led canvasses to organize our communities against Trump"}
,{title: "#ResistTrump", url: "http://resisthere.org/", cat: [campaign, trump], info: "Another portal onto #ResistTrumpTuesdays by the Working Families Party."}
,{title: "20 Lessons from the twentieth century.", url: "https://www.facebook.com/timothy.david.snyder/posts/1206636702716110", cat: [article, strategy], author: "Timothy Snyder", date: "15 Nov 2017", info: "A thought-provoking Facebook post with 20 lessons we can take away from the dictatorships of the twentieth century (Hitler, Stalin, etc.)."}
,{title: "2016 Homeless Needs Assessment", author: "City of Seattle", cat: [resource, homelessness], url: "http://coshumaninterests.wpengine.netdna-cdn.com/wp-content/uploads/2017/03/City-of-Seattle-Needs-Assesment-Report-Draft-FINAL.pdf", info: "Lots of data about homelessness in Seattle. A good place to ground discussion of the issue."}
,{title: "21 Progress", url: "https://21progress.org/", cat: [organization, community_organizing], info: "“21 Progress provides programs that empower leaders among the hard working people of Washington and advances bold ideas for economic and social justice.”"}
,{title: "3 ways you can change the conversation about immigration on Facebook.", author: "Carly Goodman", pub: "AFSC Blog.",url: "https://www.afsc.org/blogs/media-uncovered/3-ways-change-conversation-immigration-facebook", date: "18 Nov 2016", cat: [article, immigration_refugees], info: "Good explanation of arguments that can be made to common criticisms and misconceptions about immigration issues."}
,{title: "350.org", url: "https://350.org/", cat: [organization, environment], info: "Climate change movement."}
,{title: "43rd District Democrats", url: "http://43rddems.ngpvanhost.com/", cat: [organization, washington_state],info: "The fighting 43rd."}
,{title: "5 Calls", url: "https://5calls.org/", cat: [app, resource, congress], info: "Another service that organizes you and gives you five calls to make every day. I’ve heard it gives you a lot of calls to make."}
,{title: "6 Rules of Islamophobia.", url: "http://www.huffingtonpost.com/entry/islamophobia-america_us_587cf491e4b0e58057ff98e0", author: "Christopher Mathias", pub: "Huffington Post", date: "23 Jan 2017", cat: [article, religious_freedom], info: "The “6 big lies” of Islamophobia."}
,{title: "A Game Plan for Senate Democrats.", author: "Sarah Binder", pub: "New York Times", date: "10 Feb 2017", url: "https://www.nytimes.com/2017/02/10/opinion/a-game-plan-for-senate-democrats.html", cat: [article, strategy], info: "The many ways Senate democrats can procedurally slow down Republicans."}
,{title: "A guide to rebuilding the Democratic Party, from the ground up.", url: "http://www.vox.com/the-big-idea/2017/1/5/14176156/rebuild-democratic-party-dnc-strategy", author: "Theda Skicpol", pub: "Vox", date: "5 Jan 2017", cat: [article, elections], info: "This is a good corrective to a lot of unproductive talk and action these days. They agree with the Indivisble approach, focus on legislative and gubernatorial races, and note that the left has nothing financially or organizationally to counter far-right institutions (not the GOP per se)."}
,{title: "A Journalist’s Manual: Field Guide to Anti-Muslim Extremists.", url: "https://www.splcenter.org/20161025/journalists-manual-field-guide-anti-muslim-extremists", cat: [article, religious_freedom], author: "Southern Poverty Law Center", date: "25 Oct 2016", info: "Overview from Southern Poverty Law Center."}
,{title: "A message to my doomed colleagues in the American media.", url: "https://medium.com/@alexey__kovalev/message-to-american-media-from-russia-6e2e76eeae77", author: "Alexey Kovalev", pub: "Medium.com", date: "12 Jan 2017", cat: [article, media], info: "A Russian reporter notes that Trump’s press events are following the model established by Putin, (which are pure propaganda circuses). He believes the response should be to forget the press pools and engage in more investigative journalism."}
,{title: "A simple guide to how you can throw sand in the Trump administration’s gears.", url: "https://thinkprogress.org/a-simple-guide-to-how-you-can-throw-sand-in-the-trump-administrations-gears-64843da93664", cat: [article, strategy], author: "Katherine Minarik", pub: "ThinkProgress", date: "30 Jan 2017", info: "How to comment on new regulations to bring slow bad ones down or even suggest avenues for court challenges."}
,{title: "ACLU Mobile Justice App", url: "https://www.aclu.org/feature/aclu-apps-record-police-conduct", cat: [app, security], info: "Not available in all states, however."}
,{title: "AdStrike", url: "http://adstrike.us/", cat: [media, boycott], info: "Automates tweeting/FB posts asking companies to pull their advertising from Breitbart."}
,{title: "Advocates for Immigrants in Detention Northwest (AID NW)", url: "http://aidnw.org/", cat: [organization, immigration_refugees], info: "They run a few programs at the Northwest Detention Center to support detainees there."}
,{title: "All of Trump’s Russia Ties, in 7 Charts.", url: "http://www.politico.com/magazine/story/2017/03/connections-trump-putin-russia-ties-chart-flynn-page-manafort-sessions-214868", author: "Michael Crowley", pub: "Politico", date: "Mar 2017", info: "Note this does not include his extensive ties to oligarchs in former Soviet Republics.", cat: [article, trump, corruption]}
,{title: "AllSides", url: "http://www.allsides.com/", cat: [resource, news], info: "This site claims to show “all sides” of the news so as to reduce bias. More accurately I would say they cull news items with different biases so you can see them together."}
,{title: "America’s Voice", url: "http://www.americasvoice.org/", fav: true, cat: [organization, immigration_refugees], info: "They have a must read blog."}
,{title: "American Bridge PAC", url: "https://americanbridgepac.org/", cat: [resource, congress], info: "Focus on research and ad campaigns to hold Republicans accountable for their malfeasance."}
,{title: "American Civil Liberties Union", url: "https://www.aclu.org/", cat: [organization, civil_rights, privacy]}
,{title: "American Friends Service Committee", url: "https://www.afsc.org/actioncenter", cat: [organization, religious_freedom], info: "They have a blog and a mailing list, but not sure how much is happening here. However I did get a good article or two from their blog."}
,{title: "American Immigration Council", url: "https://americanimmigrationcouncil.org/", cat: [organization, immigration_refugees], info: "Looks like a think tank to me, with very comprehensive backgrounders on all aspects of immigration."}
,{title: "Americans aren't as attached to democracy as you might think.", url: "https://www.theguardian.com/commentisfree/2017/feb/11/americans-arent-attached-democracy-rule-law", author: "Austin Sarat", pub: "The Guardian", date: "11 Feb 2017", cat: [article, civil_society], info: "Title says it all, unfortunately."}
,{title: "An Alternative Strategy for Democratic Success: Growing a New Electorate.", url: "http://washingtonmonthly.com/2017/02/22/an-alternative-strategy-for-democratic-success-growing-a-new-electorate/", author: "Nancy LeTourneau", pub: "Washington Monthly", date: "22 Feb 2017", cat: [article, community_organizing, elections]}
,{title: "Anti-Defamation League", url: "http://www.adl.org/", cat: [organization, religious_freedom], info: "The ADL “fights anti-Semitism and all forms of bigotry, defends democratic ideals and protects civil rights for all.”"}
,{title: "Asian Counseling Referral Service", url: "https://acrs.org/", cat: [organization, immigration_refugees], info: "Services include application and fee waiver assistance, as well as ESL and English Citizenship classes, free, or available at low cost, to eligible applicants."}
,{title: "Autocracy: Rules for Survival.", url: "http://www.nybooks.com/daily/2016/11/10/trump-election-autocracy-rules-for-survival/", author: "Masha Gessen", pub: "New York Review of Books", date: "10 Nov 2016", cat: [article, strategy], info: "Good advice, if pessimistic (she suggests our institutions won’t fight back at all)."}
,{title: "Backbone Campaign", url: "http://www.backbonecampaign.org/", cat: [campaign, organization, environment], info: "“Backbone Campaign provides artful activism & creative organizing tools, training & action support for the 99%.”"}
,{title: "Beyond the Moment", url: "https://beyondthemoment.org/", info: "Organization coordinating protest events on May Day.", cat: [event], date: "1 May 207"}
,{title: "Bill Moyers", url: "http://billmoyers.com/", cat: [person, media], facebook: "moyersandcompany", twitter: "BillMoyersHQ", info: "Another media personality with a lot to say about Trump regime."}
,{title: "Black Lives Matter", url: "http://blacklivesmatter.com/", cat: [racial_justice, organization, campaign], info: "BLM seems very decentralized, so I’m not sure if this site is “official” per se."}
,{title: "Breitbart-led right-wing media ecosystem altered broader media agenda.", url: "http://www.cjr.org/analysis/breitbart-media-trump-harvard-study.php", author: "Benkler et all", pub: "Columbia Journalism Review", date: "3 Mar 2017", cat: [article, media]}
,{title: "Café to Go: A Quick Reference Guide for hosting World Café.", url: "http://www.theworldcafe.com/wp-content/uploads/2015/07/Cafe-To-Go-Revised.pdf", author: "The World Café", cat: [article, community_organizing], date: "2015", info: "Many community organizing meetings have followed some variant of the process described here in some depth, to find collective ideas and consensus through conversations."}
,{title: "Call My Congress", url: "https://www.callmycongress.com/", cat: [resource, congress], info: "Another site to get contact information for your legislators."}
,{title: "Call The Halls Guide", url: "https://gumroad.com/l/callthehallsguide", cat: [resource, congress], info: "A PDF guide to lobbying Congress (looks like you need to pay for it, you can pay $0) if you want or need."}
,{title: "Call Them In", url: "http://www.callthemin.com/", cat: [resource, weeklies], info: "“Timely email reminders with tailored call scripts at your fingertips, so you can oppose Donald Trump’s agenda and back progressive legislation in a meaningful way.”"}
,{title: "Calls for Change", url: "https://www.callsforchange.com/", cat: [resource, weeklies], info: "Another site that sends out calls to make."}
,{title: "Campaign to Defend Local Solutions", url: "http://defendlocal.com/", cat: [campaign, regionalism], info: "Campaign to protect city/county laws from state preemption."}
,{title: "Campaign Zero", url: "http://www.joincampaignzero.org/", cat: [campaign, racial_justice], info: "Black Lives Matter/police accountability."}
,{title: "Cascadia Climate Action Calendar", url: "http://cascadiaclimateaction.org/", cat: [calendar, environment], info: "The best calendar in Seattle for climate change events."}
,{title: "Catalytic Community Calendar", url: "http://www.catalyticcommunity.org/calendar/", cat: [calendar], info: "Another good calendar for events in Seattle."}
,{title: "Cell 411", url: "https://getcell411.com/", cat: [app, civil_society, security], info: "Keep a group of citizens informed of emergencies, the need for rides, etc. Hard to describe, but check it out. Good for activists, good for building support communities where there are hate crimes, etc."}
,{title: "Church Council of Greater Seattle", url: "http://thechurchcouncil.org/", cat: [organization, religious_freedom], info: "“The Church Council of Greater Seattle convenes and catalyzes communities and people of faith to bring our spiritual commitments of love and reconciliation, peace and justice into the public square. We aspire together to weave a world of justice through right and equitable relationships with one another.”"}
,{title: "Cities Go Rogue Against Trump and the Radical Right.", url: "http://billmoyers.com/story/cities-go-rogue-trump-radical-right/", author: "Theo Anderson", pub: "Bill Moyers.com", date: "1 Mar 2017", info: "Talks at length about the use of state preemption laws to stop progressive city ordinances, and the groups who have been involved in fighting preemption.", cat: [article, civil_society, regionalism]}
,{title: "Citizen Resource Center", url: "http://www.congressfoundation.org/citizen-engagement/citizen-resource-center", author: "Congressional Management Foundation", cat: [organization, strategy, elections, congress]}
,{title: "Citizens’ Climate Lobby", url: "http://citizensclimatelobby.org/", cat: [organization, environment], info: "Non-profit, grassroots lobby building bipartisan support for “Carbon Fee and Dividend” legislation."}
,{title: "Civic Victories.", url: "https://www.facebook.com/notes/emily-menon-bender/civic-victories/10154463245818301?hc_location=ufi", cat: [article, civil_society], info: "A list (hopefully to be maintained) of successes in opposing the regime.", author: "Emily Menon Bender"}
,{title: "Civil resistance and the “3.5% Rule”", url: "https://rationalinsurgent.com/2013/11/04/my-talk-at-tedxboulder-civil-resistance-and-the-3-5-rule/", info: "https://rationalinsurgent.com/2013/11/04/my-talk-at-tedxboulder-civil-resistance-and-the-3-5-rule/", cat: [video, strategy, civil_society], info: "3.5% of the US population is 11.2 million people, by the way."}
,{title: "Climate Change Deniers", url: "https://www.ofa.us/climate-change-deniers/", cat: [resource, congress, environment], info: "The members of Congress who deny climate change, along with arguments to call out their intransigence that are specific to their jurisdictions."}
,{title: "Climate Solutions", url: "https://www.climatesolutions.org/", cat: [organization, environment], info: "“Practical solutions to global warming.”"}
,{title: "Coalition of Anti-Racist Whites", url: "https://www.carw.org/", cat: [organization, civil_rights]}
,{title: "Code Blue", url: "https://www.codeblue.team/", cat: [organization, elections], info: "Mission: rebuild a progressive voting majority in federal, state and local government."}
,{title: "Collectiva Legal del Pueblo", url: "http://colectivalegal.org/", cat: [organization, immigration_refugees],info: "Small organization that provides legal advice and “know your rights” trainings to immigrant communities. They have some volunteer opportunities (particularly if you speak Spanish)."}
,{title: "Color of Change", url: "https://www.colorofchange.org/", cat: [resource, racial_justice], info: "An organization that provides tools to start online campaigns for racial justice."}
,{title: "Common Cause", url: "http://www.commoncause.org/", cat: [organization, civil_society, voting_rights], info: "“We work to create open, honest, and accountable government that serves the public interest; promote equal rights, opportunity, and representation for all; and empower all people to make their voices heard in the political process.” Honestly this seems like a DC outfit to me that just asks for money."}
,{title: "Communities Rising!", url: "https://www.communitiesrisingus.org/", cat: [organization, community_organizing], facebook: "CommunitiesRisingUSA", info: "A community organizing effort, a little younger than SNAC. It is also currently organizing meetings by neighborhood and planning future activities."}
,{title: "Community Environmental Legal Defense Fund", url: "http://celdf.org/", cat: [organization, environment, civil_society, regionalism], info: "“We assist communities to develop first-in-the-nation, groundbreaking laws to protect rights – including worker, environmental, and democratic rights, and rights of nature. CELDF provides free and low cost legal services, grassroots organizing, and education, to communities, states, and countries facing injustice.” Seem to have a number of Washington state initiatives."}
,{title: "Community Events Calendar", url: "https://thechurchcouncil.org/calendar/", author: "Church Council of Greater Seattle", cat: [calendar, religious_freedom], info: "Activist events sponsored by faith communities throughout Seattle."}
,{title: "Confronting Fear: Final Report", url: "http://www.islamophobia.org/images/ConfrontingFear/Final-Report.pdf", author: "Council on American-Islamic Relations", cat: [resource, religious_freedom]}
,{title: "Connecting Trump’s Dots to Russia.", url: "https://www.nytimes.com/2017/03/09/opinion/connecting-trumps-dots-to-russia.html", author: "", pub: "Nicholas Kristof", date: "9 Mar 2017", cat: [article, corruption], info: "It is hard to find a comprehensive overview of Trump’s Russian connections and the various ongoing corruption scandals. Here’s an article that summarizes a bit."}
,{title: "Contacting Congress", url: "https://www.contactingcongress.org/", cat: [resource, congress], info: "One thing I really like about this site (other than that it is fast and easy), is that it includes links to all the media accounts for each representative.", fav: true}
,{title: "Council on American-Islamic Relations", url: "https://www.cair.com/press-center/action-alerts.html", cat: [organization, religious_freedom], info: "Infrequent action alerts, and an email newsletter that documents reported hate crimes across the country and CAIR’s follow-up. Informative."}
,{title: "Countable", url: "https://www.countable.us/", cat: [app, congress, news], info: "This is a very good application for reviewing what Congress is doing each day, and for tracking specific legislation."}
,{title: "Daily Action", url: "https://dailyaction.org/", cat: [resource, weeklies], info: "“In 90 seconds, you can conscientiously object and be done with it.” This one works entirely through your phone so you can make phone calls to your elected representatives."}
,{title: "Dan Rather", url: "https://www.newsandgutsmedia.com/", cat: [person, media], info: "You know this guy.", facebook: "theDanRather", twitter: "danrather"}
,{title: "Data Refuge Project", url: "https://www.datarefuge.org", cat: [resource, science, environment], info: "One of several data stores saving climate data before it is deleted by Trump administration."}
,{title: "Defending Accounts Against Common Attacks", url: "https://source.opennews.org/en-US/guides/defending-accounts/", cat: [resource, security], info: "Securing your electronic communications."}
,{title: "Define American", url: "https://defineamerican.com/", cat: [organization, immigration_refugees], info: "Support for undocumented immigrants. See their #FactsMatter campaign for useful op-ed information."}
,{title: "Democracy 21", url: "http://www.democracy21.org/", cat: [organization, civil_society], info: "“Nonpartisan organization dedicated to making democracy work for all Americans.” Pretty dry site but they do focus on corruption and the influence of money on politics."}
,{title: "Democratic Coalition Against Trump", url:"http://www.democraticcoalition.org/", cat: [organization], info:"Resisting Trump through research, boycotts, and so forth, a good opposition site."}
,{title: "Despair Is Not A Strategy.", url: "https://medium.com/@abby.brockman/despair-is-not-a-strategy-15-principles-of-hope-deba7ac2cb29", cat: [article, self_care], author: "Abby Brockman", pub: "Medium", date: "6 Mar 2017", info: "Like the title says&hellip; work on your attitude."}
,{title: "Detention Watch Network", url: "http://www.detentionwatchnetwork.org/", cat: [organization, immigration_refugees, prison_reform], info: "“Detention Watch Network is a national membership organization that brings together advocates from diverse backgrounds to unify strategy, build partnerships and strengthen the movement to end immigration detention.”"}
,{title: "Digital Security Tips for Protesters", url: "https://www.eff.org/deeplinks/2016/11/digital-security-tips-for-protesters", cat: [resource, security], info: "Some repeated advice here, but some is unique to protests."}
,{title: "Dirty money: Trump and the Kazakh connection.", cat: [article, corruption], url: "https://www.ft.com/content/33285dfa-9231-11e6-8df8-d3778b55a923", author: "Tom Burgis", pub: "Financial Times", date: "19 Oct 2016"}
,{title: "Do A Thing", url: "http://tinyletter.com/doathing/", cat: [weeklies, mailing_list], info: "5 minutes a day activism mailing list. Like Easy Action, very easy stuff to do."}
,{title: "Don't Dismiss President Trump's Attacks on the Media as Mere Stupidity.", url: "http://time.com/4675860/donald-trump-fake-news-attacks/", author: "Bret Stephens", pub: "Time", date: "21 Feb 2017", info: "This year’s Daniel Pearl Memorial Lecture at UCLA, this is a powerful piece about Trump’s assault on the press, and the acquiescence of conservativism to Trump’s take-over of the Republican party. The speaker is a journalist with the Wall Street Journal.", cat: [article, civil_rights, media]}
,{title: "Donald Trump is Choosing His Cabinet. Here’s the Latest List.", url: "http://www.nytimes.com/interactive/2016/us/politics/donald-trump-administration.html", pub: "New York Times", cat: [resource, trump]}
,{title: "Donald Trump’s Authoritarian Politics of Memory.", url: "https://www.theatlantic.com/politics/archive/2017/01/donald-trumps-authoritarian-politics-of-memory/514004/", author: "Ruth Ben-Ghiat", pub: "The Atlantic", date: "22 Jan 2017", cat: [article, trump]}
,{title: "DuckDuckGo", url: "https://duckduckgo.com/", cat: [app, security], info: "DuckDuckGo is an Internet search engine that emphasizes protecting searchers’ privacy and avoiding the filter bubble of personalized search results."}
,{title: "Easy Action", url: "http://tumblr.us14.list-manage1.com/subscribe?u=79af7f6abbb44dfecd7a25fc7&id=4a5099043d", cat: [mailing_list, weeklies], info: "A mailing list with things to do to resist Trump every week. This is the easiest of the lot so if you are truly overwhelmed, do this one."}
,{title: "El Centro de la Raza", url: "http://www.elcentrodelaraza.org/", cat: [organization, immigration_refugees], info: "As an organization grounded in the Latino community, the organization works to build unity across all racial and economic sectors, for all the good things, like equity, freedom, and justice."}
,{title: "Electronic Frontier Foundation", url: "https://www.eff.org/", cat: [organization, privacy, technology], info: "This isn’t super sexy for a lot of people, but issues like state surveillance are critically important, and the EFF is one of the few organizations defending digitl civil liberties."}
,{title: "Everytown for Gun Safety", url:"http://everytown.org/", cat: [organization, gun_violence], info: "Everytown is a movement of Americans working together to end gun violence and build safer communities."}
,{title: "Experts in authoritarianism advise to keep a list of things subtly changing around you, so you’ll remember.", url: "https://medium.com/@Amy_Siskind", author: "Amy Siskind", cat: [person, corruption, civil_society], info: "Amy Siskind has been documenting the erosion of laws and norms since Trump came to power. It’s invaluable, and damning."}
,{title: "FactCheck.org", url: "http://www.factcheck.org/", cat: [resource, news], info: "Annenberg Public Policy Center at the University of Pennsylvania"}
,{title: "Fair Immigration Reform Movement (FAIR)", url: "https://fairimmigration.org/", cat: [organization, immigration_refugees], info: "This is not the right-wing FAIR group, which also exists."}
,{title: "Faith Action Network", url: "http://fanwa.org/", cat: [organization, religious_freedom], info: "They have a legislative agenda that is worth knowing about as it’s the practical stuff you’d want to see passed in Washington state."}
,{title: "Fear, Inc.", url: "https://islamophobianetwork.com/", cat: [resource, religious_freedom], info: "A very in-depth look at the organizations, speakers and funders of anti-Islamic extremists."}
,{title: "Fight For The Future", url: "https://www.fightforthefuture.org/", cat: [organization, campaign, civil_society, strategy], info: "Including a proposal to fund A-Teams: “Terrified about Trump? Quit your job, start an A-Team. We’ll fund it. Read this.”"}
,{title: "Fight The Good Fight Seattle", url: "http://www.ftgf-seattle.com/", cat: [calendar], info: "Another Seattle city calendar with a lot of good stuff in it."}
,{title: "Finding Steady Ground", url: "http://www.findingsteadyground.com/", cat: [resource, self_care], info: "If you feel burnt out or overwhelmed, maybe spend some time reading what this site has to say about taking care of yourself for the long haul."}
,{title: "Five Easy Steps to Prepare for Your Lobby Visit", url: "http://www.aila.org/infonet/five-steps-to-prepare-for-your-lobby-visit", cat: [resource, congress], pub: "American Immigration Lawyers Association", info: "Information about visiting your elected representatives. "}
,{title: "Flippable", url: "https://www.flippable.org/", cat: [organization, elections], info: "“Our mission is to turn America blue by building a movement to flip seats” focusing on weekly actions to flip state legislatures."}
,{title: "Foreign Policy: The Editor’s Room", url: "http://foreignpolicy.com/tag/the-e-r-podcast/", cat: [podcast], info: "This podcast was probably not always about the Trump administration. But these days it’s a very good place to hear discussion about the consequences of Trump for American foreign policy."}
,{title: "Former Mafia-linked figure describes association with Trump.", author: "Rosalind S. Helderman and Tom Hamburger", pub: "Washington Post", date: "17 May 2016", cat: [article, corruption], url: "https://www.washingtonpost.com/politics/former-mafia-linked-figure-describes-association-with-trump/2016/05/17/cec6c2c6-16d3-11e6-aa55-670cabef46e0_story.html"}
,{title: "Frightened by Donald Trump? You don’t know the half of it.", url: "https://www.theguardian.com/commentisfree/2016/nov/30/donald-trump-george-monbiot-misinformation", author: "George Monbiot", pub: "The Guardian", date: "30 Nov 2016", cat: [article, trump], info: "Despite the scary title, the article details the fact that Trump has stocked his administration with corporate propaganda hacks, many of whom were involved in Tea Party astroturfing."}
,{title: "Front and Centered", url: "http://frontandcentered.org/", cat: [organization, environment, economic_justice], info: "“A statewide coalition of organizations and groups rooted in communities of color and people with lower incomes; we’re on the frontlines of economic and environmental change.” Good climate/environmental justice information here."}
,{title: "Fuse: Together for Progress", url: "http://fusewashington.org/", cat: [organization, community_organizing], info: "I believe this organization is more active on the east side of the state, but they are involved in other campaigns."}
,{title: "FWD.us", url: "https://www.fwd.us", cat: [organization, immigration_refugees], info: "This looks like a tech-industry sponsored, pro-immigration reform organization. No Seattle chapter at this time."}
,{title: "Gender Justice League", url: "http://www.genderjusticeleague.org/", cat: [lgbtq, organization], info: "“Gender Justice League has focused on elevating civil and human rights for trans and gender diverse people by creating community through advocacy efforts and shared leadership development.”"}
,{title: "George Lakoff", url: "https://georgelakoff.com/blog/", cat: [person, strategy], twitter: "georgelakoff", facebook: "George-Lakoff-Official-165643503477608", info: "Cognitive anthropologist who has done extensive research on conservative worldviews and recently, the mindset behind the Trump voter."}
,{title: "Global Nonviolent Action Database", url: "http://nvdatabase.swarthmore.edu/", cat: [resource, strategy]}
,{title: "Government by White Nationalism Is Upon Us.", url: "http://www.slate.com/articles/news_and_politics/cover_story/2017/02/government_by_white_nationalism_is_upon_us.html", cat: [article, civil_society, trump], author: "James Bouie", pub: "Slate", date: "6 Feb 2017"}
,{title: "GovTrack", url: "https://www.govtrack.us/", cat: [resource, congress], info: "A good site to research your representative’s voting history, who is on what committee, and so forth."}
,{title: "Greater Seattle Neighborhood Action Coalition", url: "https://www.neighborhoodaction.info/", cat: [organization, community_organizing], info: "A community organizing effort. “A practical, people-powered solution to the many known and imminent threats of a dangerous and authoritarian Trump regime.” The organization has neighborhood NACs for each city district, that are meeting regularly, as well as at a meeting of all the NACs."}
,{title: "Handbook for Nonviolent Campaigns", url: "https://www.wri-irg.org/pubs/NonviolenceHandbook", cat: [resource, strategy]}
,{title: "Hate Free Delridge", url: "https://www.facebook.com/hatefreedelridge/", cat: [organization, racial_justice], info: "Anti-hate network that has extended throughout Seattle."}
,{title: "Hate Has No Home Here - Ballard Sign Crowdfund", url: "https://www.gofundme.com/hate-has-no-home-here-ballard", cat: [civil_society, campaign], info: "Funding to print out a bunch of anti-hate signs that can be distributed through Ballard inexpensively."}
,{title: "Hi From The Other Side", url: "https://www.hifromtheotherside.com/", cat: [organization, civil_society], info: "Feel alienated from the other side of the political divide? This organization arranges one-on-one conversations between people with different political beliefs so they can sort it and maybe find some common ground."}
,{title: "House and Senate Committee Contacts", url: "https://docs.google.com/spreadsheets/d/1y5QASbrOOu42RmxoxTBI6zWer89ICTvMky0b2d02Kok/edit#gid=0", cat: [resource, congress], info: "You can’t find this list very easily on the Internet. Print it out. Put it in a safe. These are the committee phone numbers for both houses of Congress.", fav: true}
,{title: "How an obscure U.S. policy effort could hurt American Muslims.", cat: [article, religious_freedom], url: "https://www.washingtonpost.com/national/how-an-obscure-policy-effort-could-hurt-american-muslims/2017/01/11/8ce93184-d76e-11e6-b8b2-cb5164beba6b_story.html", author: "Abigail Hauslohner", pub: "Washington Post", date: "11 Jan 2017", info: "Designating the Muslim Brotherhood a terrorist organization for the first time, the GOP could then use this against Muslim advocacy organizations to brand them as supporters of terrorism (and not civil rights organizations)."}
,{title: "How Congress is voting.", url: "https://www.govtrack.us/congress/votes", cat: [resource, congress], info: "Best site I’ve found for getting information on how Congress is voting."}
,{title: "How Opponents Sank A GOP Bill To Sell Off Federal Land — And What They Learned.", url: "http://www.huffingtonpost.com/entry/public-lands-battle-chaffetz_us_58a735a8e4b037d17d2778f4", author: "Chris D'Angelo", pub: "The Huffington Post", date: "26 Feb 2017", cat: [article, environment]}
,{title: "How to #StayOutraged Without Losing Your Mind: Self-Care Lessons for the Resistance.", url: "https://medium.com/the-coffeelicious/how-to-stayoutraged-without-losing-your-mind-fc0c41aa68f3#.7vx8qbhwz", cat: [article, self_care], info: "Probably everyone should read this."}
,{title: "How to Culture Jam a Populist in Four Easy Steps.", url: "https://www.caracaschronicles.com/2017/01/20/culturejam/", author: "Andrés Miguel Rondón", pub: "Caracas Chronicles", date: "20 Jan 2017", cat: [article, strategy], fav: true, info: "Lessons from fighting Chavez in Venezuela for years."}
,{title: "How to Defeat Those Who are Waging War on Science.", url: "https://blogs.scientificamerican.com/guest-blog/how-to-defeat-those-who-are-waging-war-on-science/", author: "Jonathan Foley and Christine Arena", pub: "Scientific American", date: "27 Feb 2017", info: "It’s no accident they illustrated this article with anti-science paragon, EPA Administrator Scott Pruitt.", cat: [article, strategy, science]}
,{title: "How to Get Out of the Cycle of Outrage In a Trump World.", url: "https://journal.thriveglobal.com/how-to-get-out-of-the-cycle-of-outrage-in-a-trump-world-ffc5b2aa1b5f", author: "Arianna Huffington", pub: "Thrive Global", date: "6 Feb 2017", cat: [article, self_care]}
,{title: "How to Jam The Trump Brand.", url: "https://theintercept.com/2017/04/12/how-to-jam-the-trump-brand/", author: "Naomi Klein", pub: "The Intercept", date: "12 Apr 2017", cat: [article, strategy, civil_society, trump], info: "Strategies to resist Trump by striking at his business interests."}
,{title: "How to Stand Up to Trump and Win.", url: "https://www.nytimes.com/2017/04/13/opinion/how-to-stand-up-to-trump-and-win.html", author: "Nicholas Kristof", pub: "The New York Times", date: "13 Apr 2017", cat: [article, strategy, civil_society, trump], info: "Cites the work of Gene Sharp and Jamila Raqib (scholars of nonviolent resistance) as tactics that can work to bring authoritarians like Trump."}
,{title: "How To Topple a Dictator (inteview with Erica Chenoweth).", url: "https://www.thenation.com/article/how-to-topple-a-dictator/", info: "Chenoweth’s research points to the importance of numbers in nonviolent mobilization. Numbers matter. Nonviolent movements can achieve this because they can involve more and more sectors of society&mdash;indeed they must do this, or they will probably fail.", author: "Waleed Shahid", pub: "The Nation", date: "24 Feb 2017", cat: [article, strategy, civil_society]}
,{title: "How to Write a Letter to the Editor.", url: "http://www.outdooralliance.org/blog/2017/3/13/how-to-write-a-letter-to-the-editor", pub: "Outdoor Alliance", cat: [article, strategy], info: "Tips for your letter to the editor."}
,{title: "Human Rights Campaign", url: "https://www.hrc.org/", cat: [organization, lgbtq]}
,{title: "Immigrant Ally Toolkit", url: "https://www.indivisibleguide.com/resources/online/immigrant-ally-toolkit/", pub: "Indivisible", cat: [resource, immigration_refugees], info: "A toolkit for activists wanting to become allies on immigration issues (if you are directly impacted by these policies, there are better resources listed here for you)."}
,{title: "Immigration Impact", url: "https://immigrationimpact.com/", cat: [organization, immigration_refugees], pub: "American Immigration Council", info: "Another public policy organization devoted to immigration. Lots of comprehensive information."}
,{title: "Indivisible Action Calendar/Capitol Calendar", url: "https://www.indivisibleguide.com/action-calendar", cat: [calendar], info: "This has a good summary of activities happening in Congress, and what you should focus on when calling."}
,{title: "Indivisible Radio", url: "http://www.wnyc.org/shows/indivisible/", cat: [podcast, elections], info: "“Indivisible is public radio’s national conversation about America in a time of change.” It’s a call-in show."}
,{title: "Indivisible Washington", url: "http://indivisibleguidewa.com/", cat: [resource, congress, elections], info: "This resource tries to be a clearinghouse of information for indivisible groups across the state"}
,{title: "Indivisible: A Practical Guide for Resisting the Trump Agenda", url: "https://www.indivisibleguide.com/", cat: [resource, strategy, community_organizing], info: "“Former congressional staffers reveal best practices for making Congress listen.” In addition to a strategy guide that is being widely read right now, they are organizing local chapters that are pursuing this strategy, please take a look."}
,{title: "Informed Immigrant", url: "https://www.informedimmigrant.com/", cat: [immigration_refugees, resource], info: "Lots of information for immigrants on rights, current laws, etc. Good resource for further research."}
,{title: "Inspire Seattle", url: "http://inspireseattle.org/", cat: [organization, community_organizing], info: "Works “to create connection throughout our community and better community through activism” through “fun, supportive gatherings” to pursue progressive politics."}
,{title: "International Rescue Committee", url: "https://www.rescue.org/", cat:  [organization, immigration_refugees], info: "There’s lots of ways to volunteer to help and this seems like a great organization, it is dealing with documented immigrants and refugees."}
,{title: "Islam Fact Check", url: "http://islamfactcheck.org/", cat: [resource, religious_freedom]}
,{title: "Jitsi", url: "https://jitsi.org/", cat: [app, security], info: "Secure (encrypted) video calls and chat"}
,{title: "K-12 Coalition to Protect Undocumented Students", url: "http://www.undocustudentcoalitionwa.org/", cat: [organization, immigration_refugees], info: "“All students, regardless of immigration status, have a constitutional right to attend public K-12 education (Plyler vs. Doe, 457 U.S. 202, 1982).... we urge Washington State school districts to support their school staff, undocumented students and families through the following 3 recommended actions...”"}
,{title: "Kids in Need of Defense (KIND)", url: "https://supportkind.org/", cat: [organization, immigration_refugees], info: "KIND represents unaccompanied immigrant and refugee children in their deportation proceedings."}
,{title: "Know Your Rights Flyers, Posters & Trainings", url: "https://www.immdefense.org/ice-home-and-community-arrests/", cat: [resource, immigration_refugees], info: "Good KYR flyers in many languages, as well as posters explaining what should be documented if you witness an immigration raid. Very good after-the-fact prompts to write down all that is known about an incident."}
,{title: "Know Your Rights", url: "http://unitedwedream.org/thank-deportation-defense-card-handy-phone/", author: "United We Dream", cat: [resource, immigration_refugees], info: "Good KYR cheat sheets, phone sized, several languages, and a hotline to call if you see ICE agents."}
,{title: "Lambda Legal", url: "https://www.lambdalegal.org/", cat: [organization, lgbtq]}
,{title: "Lawyers’ Committee for Civil Rights Under Law", url: "https://lawyerscommittee.org/", cat: [organization, civil_rights], info: "In addition to civil rights cases, this organization was very active in receiving reports of vote irregularities during the election."}
,{title: "League of Conservation Voters Scorecard", url: "http://scorecard.lcv.org/", cat: [resource, environment], info: "Environmental voting history of your reps."}
,{title: "Let America Vote", url: "https://www.letamericavote.org/", cat: [organization, voting_rights], info: "New organization started by Jason Kander to focus on voting rights."}
,{title: "Lightning Bolt", url: "http://www.lightningbolt.vision/", cat: [resource, civil_society], info: "Prepper culture for leftists."}
,{title: "Make It Work", url: "http://www.makeitworkcampaign.org/", cat: [campaign], info: "A three-year education campaign advocating for raising wages, closing the pay gap, more affordable child and elder care, and providing family leave."}
,{title: "MALDEF (The Latino Legal Voice for Civil Rights in America)", url: "http://www.maldef.org/", cat: [organization, civil_rights, immigration_refugees]}
,{title: "May Day March for Workers and Immigrant Rights", url: "https://www.facebook.com/events/1600651136614959/", date: "1 May 2017", cat: [event, immigration_refugees, civil_society]}
,{title: "Migration Policy Institute", url: "http://www.migrationpolicy.org/", cat: [organization, immigration_refugees], info: "A DC think tank with lots of research on the migration of people worldwide."}
,{title: "Moms Demand Action", url: "http://momsdemandaction.org/", cat: [organization, gun_violence], info: "“Much like Mothers Against Drunk Driving was created to reduce drunk driving, Moms Demand Action for Gun Sense in America was created to demand action from legislators, state and federal; companies; and educational institutions to establish common-sense gun reforms.”"}
,{title: "Movement 2017", url: "http://movementvote.org/", cat: [resource, elections]}
,{title: "Muslim Association of Puget Sound", url: "http://www.mapsredmond.org/", cat: [organization, religious_freedom], info: "They have been responding to vandalism of mosques in our region (at the least, there’re probably doing more)."}
,{title: "NAACP", url: "http://www.naacp.org/", cat: [organization, racial_justice], info: "“The NAACP is the nation’s oldest, largest and most widely recognized grassroots-based civil rights organization.”"}
,{title: "NARAL Pro-Choice America", url: "http://www.naral.org/", cat: [organization, womens_rights]}
,{title: "National Democratic Party", url: "https://www.democrats.org/", cat: [organization, congress], info: "The opposition party."}
,{title: "National Democratic Redistricting Committee", url: "https://democraticredistricting.com/", cat: [organization, congress, voting_rights]}
,{title: "National Immigration Forum", url: "http://immigrationforum.org/", cat: [organization, immigration_refugees]}
,{title: "National Popular Vote", url: "http://www.nationalpopularvote.com/", cat: [campaign, voting_rights], info: "“The National Popular Vote bill would guarantee the Presidency to the candidate who receives the most popular votes in all 50 states and the District of Columbia.” Does not require amendment to the constitution, but would require all compact states to follow the compact. I was skeptical of this but there has been progress on it."}
,{title: "Natural Resources Defense Council", url: "https://www.nrdc.org/", cat: [organization, environment], info: "“The Natural Resources Defense Council works to safeguard the earth.”"}
,{title: "Nifty Fifty", url: "https://www.fiftynifty.org/", cat: [campaign, congress], info: "“This is a grassroots challenge to get friends in 50 states to make calls to their congresspeople about an issue they care about.” To a greater extent than similar projects, this effort seeks to extend networks across the country."}
,{title: "Northwest Detention Center Resistance", url: "http://www.nwdcresistance.org/", cat:[organization, campaign, immigration_refugees], info: "Based in Tacoma, they are the best resource to keep apprised of what is happening at the Northwest Detention Center."}
,{title: "Northwest Immigrant Rights Project", url: "https://www.nwirp.org/", cat: [organization, immigration_refugees], info: "Volunteer opportunities: general intake volunteers (college students looking to enter law school); volunteer translators/interpreters; document processing volunteers."}
,{title: "Obamacare is working and repealing it would be a catastrophe.", url: "https://www.ofa.us/why-obamacare-matters/", pub: "Organizing for Action", cat: [resource, healthcare], info: "This is a large collection of resources to draw upon when advocating for the ACA. With handy ways to share each resource on social media&hellip;it’s a good idea for other causes."}
,{title: "Office of Immigrant and Refugee Affairs, City of Seattle", url: "http://www.seattle.gov/iandraffairs", cat: [immigration_refugees, organization], info: "There’s a lot of good data here about immigrant and refugee communities in our city."}
,{title: "One America", url: "http://weareoneamerica.org/", cat: [organization, immigration_refugees], info: "“OneAmerica’s mission is to advance the fundamental principles of democracy and justice through building power in immigrant communities, in collaboration with key allies.” I have met OneAmerica organizers at events, they are out there."}
,{title: "Open States", url: "https://openstates.org/wa/", cat: [resource, congress], info: "Very good site for looking up committees, bills, representatives at the state level."}
,{title: "OpenSecrets", url: "http://www.opensecrets.org/search", cat: [resource, congress],info: "Voting records and positions."}
,{title: "Organizing for Action", url: "https://www.facebook.com/OFA/", cat: [organization, community_organizing],info: "This was originally an organization to support Obama’s presidency, it has recently become a little more active in organizing against Trump."}
,{title: "Our States", url: "https://www.ourstates.org/", cat: [resource, congress], info: "Blocking the Republican agenda state-by-state, in the state legislatures. A simple but very helpful guide."}
,{title: "People are in the streets protesting Donald Trump. But when does protest actually work?", url: "https://www.washingtonpost.com/news/monkey-cage/wp/2016/11/21/people-are-in-the-streets-protesting-donald-trump-but-when-does-protest-actually-work/", author: "Erica Chenoweth", pub: "Washington Post", date: "21 Nov 2016", cat: [article, strategy], info: "Yes, and the author explains when and why they do. Good overview of nonviolent resistance campaigns."}
,{title: "People for Washington", url: "http://peopleforwashington.com/", facebook: "peopleforWAexit", cat: [organization, regionalism], info: "Washington independence movement. #waexit"}
,{title: "People-Powered Campaign", url: "https://peoplepower.org/", author: "ACLU", cat: [organization, civil_rights], info: "People-Power activists have met with the police throughout the Puget Sound region to advocate against police cooperation with deportation forces. They will expand to other civil rights issues (in Seattle, that will include surveillance and police oversight policies)."}
,{title: "People’s Climate March, Seattle", url: "https://seattlepcm.wixsite.com/climatemarch17", date: "29 Apr 2017", info: "March for climate, jobs and justice.", cat: [event, environment]}
,{title: "People’s Climate March", url: "https://peoplesclimate.org/", date: "29 Apr 2017", info: "March for climate, jobs and justice.", cat: [event, environment]}
,{title: "Planned Parenthood", url: "https://www.plannedparenthood.org/", cat: [organization, healthcare, womens_rights], info: "In most advanced industrial countries, family planning is a part of the health care provided by the government to all its citizens, but in America&hellip;"}
,{title: "Pod Save America", url: "https://getcrookedmedia.com/here-have-a-podcast-78ee56b5a323#.x3p0xgjq9", cat: [podcast, news], pub: "Crooked Media", info: "The successor to “Keepin’ it 1600”."}
,{title: "Political Research Associates", url: "http://www.politicalresearch.org/", cat: [organization, civil_rights, strategy], info: "A lot of excellent resources here on the Right Wing and on how to respond to everything from militias taking over your town, to defending reproductive freedoms(!)", fav: true}
,{title: "PolitiFact", url: "http://www.politifact.com/", cat: [resource, news], info: "Washington Post and Tampa Bay Times?"}
,{title: "PopVox", url: "https://www.popvox.com/", cat: [organization, elections, congress], info: "Another site to track state and federal legislatures. I did not find it very helpful."}
,{title: "Presterity", url: "https://presterity.org/", cat: [resource, trump], info: "Another fact-checking site entirely devoted to Trump. Not sure yet how useful or up-to-date this site is."}
,{title: "Prison Divestment Movement", url: "https://prisondivest.com/", cat: [organization]}
,{title: "Progcode", url: "http://www.progcode.co/", cat: [technology, organization]}
,{title: "Project 1461", url: "https://www.project1461.org/", cat: [mailing_list, weeklies], info: "Another daily email of actions to take, fairly substantive with a lot of education/reading included."}
,{title: "Project Vote", url: "http://www.projectvote.org/", cat: [organization, voting_rights]}
,{title: "Prospects for the American press under Trump.", cat: [article, media], url: "http://pressthink.org/2016/12/prospects-american-press-trump-part-two/", author: "Jay Rosen", pub: "PressThink", date: "28 Dec 2016", info: "Second article on how the press might respond."}
,{title: "ProtonMail", url: "https://protonmail.com/", cat: [resource, security], info: "Secure email based in Switzerland."}
,{title: "Radical Women", url: "http://www.radicalwomen.org/", cat: [womens_rights, racial_justice, economic_justice, organization], info: "“Radical Women is the revolutionary wing of the women’s movement and a strong feminist voice within the Left.” Organization has a chapter in Seattle."}
,{title: "re:act", url: "https://www.reactletter.com/", cat: [resource, weeklies],  info: "“re:act is a list of a few concrete things you can do to take action during the Trump presidency.” This one is long but it is emerging as one of my favorite of the weekly emails that are out there."}
,{title: "Readings on Nonviolence.", author: "Gene Sharp", pub: "Albert Einstein Institute", url: "http://www.aeinstein.org/free-resources/free-publications/english/", cat: [resource, strategy], info: "Sharp has been called the Clausewitz of nonviolent struggle. Some deep (and lengthy) strategic analysis here in “How Nonviolent Struggle Works” or “From Dictatorship to Democracy.”"}
,{title: "Reform Immigration For America", url: "https://reformimmigrationforamerica.org/", cat: [organization, immigration_refugees], info: "National campaigns to work toward workable, humane, comprehensive immigration reform."}
,{title: "Refuse Facism", url: "https://refusefascism.org/", cat: [campaign, trump], info: "Leftist group that wants to force Trump/Pence out of power."}
,{title: "Register Blue", url: "https://registerblue.com/", cat: [organization, elections], info: "Campaign to register as many blue voters, especially in red districts, as possible."}
,{title: "Register Me First", url: "https://registermefirst.com/", cat: [campaign, racial_justice, religious_freedom], author: "CAIR", info: "“If they want to register American Muslims, they’ll have to #RegisterMeFirst.” A promise to sign such a registry en masse."}
,{title: "Repeal and Replace Dave Reichart", url: "https://www.repealandreplacedavereichert.com/", cat: [campaign, elections, congress], info: "Campaign to repeal and replace WA-8 congressional district’s Trump-defending congresscritter."}
,{title: "Republicans were wildly successful at suppressing voters in 2016.", cat: [article, voting_rights, gop],  url: "https://thinkprogress.org/2016-a-case-study-in-voter-suppression-258b5f90ddcd", author: "Alice Ollstein and Kira Lerner", pub: "Think Progress", date: "15 Nov 2016", info: "“Last week, the first election in 50 years without the full protection of the federal Voting Rights Act propelled Donald Trump to the White House.”", fav:true}
,{title: "Research says there are ways to reduce racial bias. Calling people racist isn’t one of them.", url: "http://www.vox.com/identities/2016/11/15/13595508/racism-trump-research-study", author: "German Lopez", pub: "Vox", date: "15 Nov 2016", cat: [article, strategy, racial_justice]}
,{title: "Resistance Calendar", url: "https://www.resistancecalendar.org/", cat: [calendar], info: "National event calendar."}
,{title: "Resistance from within: Federal workers push back against Trump.", url: "https://www.washingtonpost.com/politics/resistance-from-within-federal-workers-push-back-against-trump/2017/01/31/c65b110e-e7cb-11e6-b82f-687d6e6a3e7c_story.html", author: "Juliet Eilperin, Lisa Rein, and Marc Fisher", pub: "Washington Post", date: "31 Jan 2017", cat: [article, civil_society]}
,{title: "Resistance Resources", url: "http://www.pantsuitresources.com/", cat: [resource, trump, congress, strategy], info: "aka Pantsuit Resources, another research effort underway."}
,{title: "ResistBot", fav: true, url: "https://resistbot.io/", cat: [weeklies, congress, resource], info: "Brilliant SMS-based bot that will allow you to write Congress while you’re on the bus, or anywhere else. Text Resist to 50409 to get started."}
,{title: "ReWa", url: "http://www.rewa.org/get-involved/volunteer-opportunities/", cat: [organization, immigration_refugees], info: "An organization that specifically helps with refugee relocation to our area."}
,{title: "RISE When We Fall", url: "https://risewhenwefall.org/#pledge", info: "I’m confused about this site, but give them your email and they send you lots of information about what your representatives are doing, including town halls, their votes, etc.", cat: [resource, congress]}
,{title: "RiseUp", url: "https://riseup.net/", cat: [organization, security], info: "Provides email, mailing lists, and private wikis for activists and activist organizations."}
,{title: "Robert Reich’s First 100 Days Resistance Agenda.", url: "http://www.alternet.org/election-2016/robert-reichs-first-100-days-resistance-agenda", author: "Robert Reich", pub: "AlterNet.org", date: "19 Nov 2016", cat: [article, strategy]}
,{title: "Robert Reich", url: "http://robertreich.org/", cat: [person, strategy], info: "Former Secretary of Labor who is very vocal in opposition to Trump."}
,{title: "Run For Something", url: "https://www.runforsomething.net/", cat: [organization, elections], info: "Another organization recruiting political candidates under the age of 35."}
,{title: "Safe Zone Project", url: "http://thesafezoneproject.com/", cat: [resource, lgbtq], info: "“A free online resource for creating powerful, effective LGBTQ awareness and ally training workshops.”"}
,{title: "Sanctuary Movement", url: "http://www.sanctuarynotdeportation.org/", cat: [campaign, immigration_refugees, religious_freedom], info: "“A growing movement of immigrant and over 700 faith communities doing what Congress and the Administration refuse to do: protect and stand with immigrants facing deportation.” There is a little activity at this site, as churches respond to recent administration attacks on immigrants."}
,{title: "Scholars Strategy Network", url: "http://www.scholarsstrategynetwork.org/", cat: [organization, strategy]}
,{title: "Seattle Indivisible", url: "https://www.seattleindivisible.com/", cat: [organization, elections, congress]}
,{title: "Seattle Jewish Federation of Greater Seattle", url: "https://www.jewishinseattle.org/", cat: [organization, religious_freedom], info: "They wrote a letter strongly condemning Bannon appointment."}
,{title: "Seattle Resistance and Solidarity Calendar", url: "http://www.thestranger.com/events/resistance", pub: "The Stranger", cat: [calendar], info: "The Stranger’s calendar of events in Seattle."}
,{title: "Secure Communication", url: "https://www.circl.lu/pub/dfak/SecureCommunication/", author: "Computer Incident Response Center", cat: [resource, security], info: "A very good security explainer that assumes no prior knowledge of any kind."}
,{title: "Security in a Box", url: "https://securityinabox.org/", cat: [resource, security], info: "A very exhaustive web site on every aspect of digital and online security. Almost everyone can learning something by spending time at this site."}
,{title: "Shoulder to Shoulder", url: "http://www.shouldertoshouldercampaign.org/", cat: [campaign, religious_freedom], info: "“Standing with American Muslims; Upholding American Values.”"}
,{title: "Showing Up For Racial Justice (SURJ)", url: "http://www.showingupforracialjustice.org/", cat: [organization, racial_justice], info: "“SURJ is a national network of groups and individuals organizing White people for racial justice.”"}
,{title: "Signal", url: "https://whispersystems.org/", cat: [app, security], info: "Encrypted messaging app. The Electronic Frontier Foundation recommends this app."}
,{title: "Sin Fronteras Resource Guide: A List of Services for Immigrants in our Community [PDF].", url: "https://thechurchcouncil.org/wp-content/uploads/2016/09/SinFronterasGuide-2.pdf", author: "The Church Council of Greater Seattle", cat: [resource, immigration_refugees], info: "Resources pamphlet for King and Pierce Counties. Advocacy groups are listed here as well."}
,{title: "Sister District Project", url: "https://www.sisterdistrict.com/", cat: [campaign, elections], info: "“If you live in a safe blue or red district, your economic and volunteer resources can be channeled to a swing district that needs your help. We can change the map together.”"}
,{title: "Sleeping Giants", url: "https://www.facebook.com/slpnggiants/", cat: [boycott, media], info: "This group is working on a campaign to pull advertisers from Breitbart and eventually, other right-wing hate sites."}
,{title: "So That Happened", url: "https://itunes.apple.com/us/podcast/so-that-happened/id945384774", pub: "Huffington Post", cat: [podcast, news]}
,{title: "Solidarity Is", url: "https://www.solidarityis.org/", cat: [campaign, racial_justice], info: "“Standing in deep, multiracial solidarity, we pledge&hellip;” Training materials and examples of extensive attempts to build solidarity between communities."}
,{title: "Southern Coalition for Social Justice", url: "http://www.southerncoalition.org/", cat: [organization, voting_rights, economic_justice]}
,{title: "Southern Poverty Law Center", url: "https://www.splcenter.org/", cat: [organization, racial_justice], info: "The SPLC continues to do important research on hate organizations. It is a useful resource."}
,{title: "Spreadsheet of nomination process", url: "https://docs.google.com/spreadsheets/d/1Nx970-5j0ls4aJbmiKqwN0E3OfcpAqhXgM3zyfBZ4TM/htmlview?usp=sharing&sle=true#", cat: [resource, congress], info: "Who has gone through committee, when they are voting on whom."}
,{title: "Stand Up Republic", url: "https://standuprepublic.com/", cat: [organization, congress], info: "A conservative organization formed by Evan McMullin and Mindy Finn to resist Trump regime. Great to see resistance across the political spectrum."}
,{title: "State Innovation Exchange", url: "https://stateinnovation.org/", cat: [organization, regionalism, civil_society], info: "“Advancing progressive change in the states.”"}
,{title: "State of the Swamp", url: "https://stateoftheswamp.com/", cat: [resource, trump, corruption], info: "“Ethics in President Trump’s first 100 days”"}
,{title: "Statisticians fear Trump White House will manipulate figures to fit narrative.", url: "https://www.theguardian.com/us-news/2017/jan/30/statistics-trump-administration-numbers-manipulation", author: "Mona Chalabi", pub: "The Guardian", date: "30 Jan 2017", info: "Not all doom and gloom, but this article reviews the possibilities for administration malfeasance in this area.", cat: [article, corruption]}
,{title: "Surveillance Self-Defence", url: "https://ssd.eff.org/", cat: [resource, security]}
,{title: "SwingLeft", url: "https://swingleft.org/", cat: [campaign, elections], info: "Finds a swing district near you so you can support a Democrat and keep them in the House."}
,{title: "Talking Points Memo", url: "http://talkingpointsmemo.com/", cat: [news], info: "The daily headlines here tend to be attention grabbing and don’t always weed out the critical news from the chaffe. However the editor, Josh Marshall, has very good analyses of political developments."}
,{title: "Techs and Balances", url: "http://www.techsandbalances.org/", cat: [technology, organization]}
,{title: "The 65", url: "http://thesixtyfive.org/", cat: [resource, congress], info: "Calling scripts on virtually all issues."}
,{title: "The Action Network", url: "https://actionnetwork.org/", cat: [organization, strategy], info: "Free to individuals and small groups, this company provides support for large mailing lists. Probably not that useful over a mailing list service if you’re small."}
,{title: "The CAIR Project", url: "https://cairproject.org/", cat: [organization, womens_rights], info: "A Northwest abortion fund... “We provide referrals, fundraising counseling, and financial help to pay for abortions. Funding is sent directly to the clinic.”"}
,{title: "The Center for Popular Democracy", url: "https://populardemocracy.org/", cat: [organization], info: "National organization that seems to do everything, partnered with Working Washington in our state."}
,{title: "The Corleones of the Caspian: How Azerbaijan’s dictator woos the United States and Europe.", url: "http://foreignpolicy.com/2014/06/10/the-corleones-of-the-caspian/", author: "Michael Weiss", pub: "Foreign Policy", date: "10 Jun 2014", cat: [article, corruption]}
,{title: "The Curious World of Donald Trump’s Private Russian Connections.", cat: [article, trump], url: "http://www.the-american-interest.com/2016/12/19/the-curious-world-of-donald-trumps-private-russian-connections/", author: "James S. Henry", pub: "The American Interest", date: "19 Dec 2016", info: "“…whatever the nature of President-elect Donald Trump’s relationship with President Putin, he has certainly managed to accumulate direct and indirect connections with a far-flung private Russian/FSU network of outright mobsters, oligarchs, fraudsters, and kleptocrats.”"}
,{title: "The Dangerous Path: Big Money’s Plan to Shred the Constitution", url: "http://www.commoncause.org/issues/more-democracy-reforms/constitutional-convention/", cat: [resource, civil_society, congress], info: "Mostly GOP-controlled states are only 7 states short of having enough state resolutions to hold an Article V constitutional convention. They could rewrite the constitution if this happens, but it has never been done before so no one knows exactly how it would go, or what controls would exist on the process."}
,{title: "The Emoluments Clause: Its text, meaning, and application to Donald J. Trump.", url: "https://www.brookings.edu/research/the-emoluments-clause-its-text-meaning-and-application-to-donald-j-trump/", author: "Norman Eisen etc. al", pub: "The Brookings Institute", date: "16 Dec 2016", info: "“The Emoluments Clause, until recently not much discussed because its constraints have been taken for granted, constitutes a clear barrier to the intermingling of business and governmental interests that Donald J. Trump proposes to build into his conduct of the Presidency.”", cat: [article, civil_society]}
,{title: "The End of Identity Liberalism.", url: "https://www.nytimes.com/2016/11/20/opinion/sunday/the-end-of-identity-liberalism.html", author: "Mark Lilla", pub: "New York Times", date: "18 Nov 2016", cat: [article, strategy], info: "This is a controversial opinion piece about why the Democrats lost. However, Democrats have entirely lost white working class voters outside of the urban areas, so it’s a view that we have to wrestle with."}
,{title: "The GOP’s Age of Authoritarianism Has Only Just Begun.", url: "http://nymag.com/daily/intelligencer/2016/10/the-gops-age-of-authoritarianism-has-only-just-begun.html?mid=twitter-share-di", author: "Jonathan Chait", pub: "New York Magazine", date: "30 Oct 2016", cat: [article, gop]}
,{title: "The Movement for Black Lives", url: "https://policy.m4bl.org/", cat: [campaign, racial_justice], info: "A detailed platform for the Black Lives Matter movement. "}
,{title: "The Myth of the Rust Belt Revolt.", url: "http://www.slate.com/articles/news_and_politics/politics/2016/12/the_myth_of_the_rust_belt_revolt.html", author: "Konstantin Kilibarda and Daria Roithmayr", pub: "Slate", date: "1 Dec 2016", cat: [article, elections]}
,{title: "The People’s Calendar", url: "https://www.risestronger.org/events", pub: "RiseStronger", cat: [calendar], info: "Nation-wide calendar with events in Washington state."}
,{title: "The president lays the groundwork for a nationwide voter intimidation program.", url: "https://www.washingtonpost.com/opinions/the-president-lays-the-groundwork-for-a-nationwide-voter-intimidation-program/2017/02/14/ef524326-f2dd-11e6-a9b0-ecee7ce475fc_story.html", author: "Sherrilyn Ifill (NAACP)", pub: "Washington Post", date: "14 Feb 2017", cat: [article, voting_rights]}
,{title: "The Resistance Manual", url: "https://www.resistancemanual.org/Resistance_Manual_Home", fav: true, cat: [resource, strategy], info: "Launched by Black Lives Matter activities (I think), it’s a wiki collecting resources, strategies, etc. This is the most important resource in this list of bookmarks."}
,{title: "The Resistance Report", url: "https://www.youtube.com/playlist?list=PLQCjiNAdri5xjQyG8ytpWV59H2qeZO7CF", author: "Robert Reich", info: "A video blog about... the resistance.", cat: [civil_society, strategy, video]}
,{title: "The Resurgent Left", url: "http://www.theresurgentleft.org/", cat: [organization, elections], info: "Another organization targeting vulnerable seats."}
,{title: "The slow-motion decline: Resisting the gradual erosion of democratic institutions under President Trump.", url: "http://www.salon.com/2016/11/27/the-slow-motion-decline-resisting-the-gradual-erosion-of-democratic-institutions-under-president-trump/", author: "Simon Malloy", pub: "Salon", date: "27 Nov 2016", cat: [article, civil_society]}
,{title: "The Spy Who Wrote the Trump-Russia Memos: It Was 'Hair-Raising' Stuff.", url: "http://www.motherjones.com/politics/2017/01/spy-who-wrote-trump-russia-memos-it-was-hair-raising-stuff", author: "David Corn", pub: "Mother Jones", date: "13 Jan 2017", cat: [article, corruption]}
,{title: "The voting rights manifesto: a state-by-state plan to defend democracy.", author: "Daniel Nichanian", pub: "Vox", url: "http://www.vox.com/the-big-idea/2016/12/15/13957714/voting-rights-states-ballot-franchise-civil-rights", info: "“Access to the franchise is now the object of an all-out political battle. Those committed to protecting people’s right to vote — as well as their actual ability to exercise this right — must organize accordingly.”", date: "15 Dec 2016", cat: [article, voting_rights] }
,{title: "The Weeds", url: "http://www.vox.com/the-weeds", pub: "Vox", cat: [podcast, news]}
,{title: "These Bernie Alums Think They’ve Found the Secret to Reaching Trump Voters.", author: "Tim Murphy", pub: "BillMoyers.com", date: "3 Mar 2017", url: "http://billmoyers.com/story/bernie-alums-think-theyve-found-secret-reaching-trump-voters/", info: "Intriguing article about “deep canvassing” efforts like SwingLeft.", cat: [article, elections]}
,{title: "Toolkit to Defend Against ICE Raids and Community Arrests", url: "http://www.immdefense.org/raids-toolkit/", cat: [resource, immigration_refugees, civil_rights], info: "Very detailed discussion of past ICE practices and preparation for the future."}
,{title: "Tor Browser", url: "https://www.torproject.org/", cat: [app, security], info: "An open source web browser that helps defend you against traffic analysis, a form of network surveillance. Easy and important to use in some contexts."}
,{title: "Town Hall Project 2018", url: "https://townhallproject.com/", cat: [resource, congress], fav: true, info: "A list of all town hall and other public meetings that Congress are holding, all across the union."}
,{title: "Tracking Congress In The Age of Trump", url: "https://projects.fivethirtyeight.com/congress-trump-score/", author: "FiveThirtyEight", cat: [resource, congress], info: "A great summary of voting along with Trump or against him, you can easily find politicians who can and should be replaced, such Dean Healler (R-NV) or Cory Gardner (R-CO) who have voted 100% with Trump, though their districts leaned Clinton. There are more."}
,{title: "Training for Change", url: "https://www.trainingforchange.org/tools", cat: [resource, strategy, community_organizing]}
,{title: "Trump Confirmations", url: "https://www.washingtonpost.com/graphics/politics/trump-administration-appointee-tracker/database/", cat: [resource, trump], info: "Tracking about 700 executive positions that Trump will appoint that have to be confirmed by Congress. Will any grifter be denied a post? Visit this site to find out."}
,{title: "Trump Promise Checker", url: "https://www.washingtonpost.com/graphics/politics/trump-promise-tracker/", pub: "Washington Post", info: "Another Trump fact checking site. All the promises on this site are specific and evil.", cat: [resource, trump]}
,{title: "Trump Promised", url: "https://trumppromised.us/", cat: [resource, trump], info: "A running tally of all the things Trump has promised, and whether or not he has so far fulfilled that promise. Mostly, he promised to be evil and punch down."}
,{title: "Trump, His Children, and 500+ Potential Conflicts of Interest.", url: "http://www.wsj.com/graphics/donald-trump-potential-conflicts-of-interest/", author: "Joel Eastwood, Coulter Jones and Julia Wolfe", pub: "Wall Street Journal", date: "19 Jan 2017", cat: [article, corruption]}
,{title: "Trump’s (and Putin’s) Plan to Dissolve the EU and NATO.", url: "http://talkingpointsmemo.com/edblog/trump-s-and-putin-s-plan-to-dissolve-the-eu-and-nato", author: "Josh Marshall", "pub": "Talking Points Memo", date: "15 Jan 2017", cat: [article, trump]}
,{title: "Trump’s 7 Techniques to Control the Media.", url: "http://www.alternet.org/media/robert-reich-trumps-7-techniques-control-media",  author: "Robert Reich", pub: "AlterNet", date: "28 Nov 2016", cat: [article, media]}
,{title: "TrumpCast", url: "http://www.slate.com/articles/podcasts/trumpcast.html", cat: [podcast, news], pub: "Slate", info: "Sadly, still relevant after the election, and still posting episodes."}
,{title: "Twitter Activist Security.", url: "https://medium.com/@thegrugq/twitter-activist-security-7c806bae9cb0#.sh7dfsy9f", cat: [article, media, security], info: "Security for twitter users.", date: "29 Jan 2017"}
,{title: "Twitter list of alternative government accounts", url: "https://twitter.com/alxdark/lists/altgovaccts", cat: [resource, civil_society, science], info: "After Trump tried to censor government agencies, many formed rogue accounts to continue voicing their concerns about his attack on science and truth."}
,{title: "U.S. House Twitter accounts", url: "https://twitter.com/gov/lists/us-house", cat: [resource, congress]}
,{title: "U.S. Senate Twitter accounts", url: "https://twitter.com/gov/lists/us-senate/members", cat: [resource, congress]}
,{title: "Ultraviolet", url: "https://weareultraviolet.org/", cat: [organization, womens_rights], info: "“UltraViolet is a powerful and rapidly growing community of people from all walks of life mobilized to fight sexism and expand women’s rights, from politics and government to media and pop culture.”"}
,{title: "Understanding Trump.", url: "https://georgelakoff.com/2016/07/23/understanding-trump-2/", cat: [article, trump], info: "Another explanation for why social conservatives support Trump. (Social conservatives are disturbing as described by Lakoff, but it does explain the unexplainable.)"}
,{title: "Unite Guide", url: "http://www.uniteguide.com/", cat: [resource, elections, community_organizing], info: "How we used social media to organize about 1m people across 50 states since the week of the 2016 presidential election.”"}
,{title: "United to Protect Democracy", url: "https://unitedtoprotectdemocracy.org/", cat: [organization, civil_society], info: "“a nonpartisan nonprofit with an urgent goal: to hold the President and the Executive Branch accountable to the laws and longstanding practices that have protected our democracy through both Democratic and Republican Administrations...”"}
,{title: "United We Dream", url: "http://weareuwd.org/", cat: [organization, immigration_refugees], info: "Focused on immigrants with DACA and DAPA status, as well as higher education issues for “Dreamers”."}
,{title: "Vote Riders", url: "http://www.voteriders.org/", cat: [organization, voting_rights]}
,{title: "Voter Identification Laws and the Suppression of Minority Votes.", url: "http://pages.ucsd.edu/~zhajnal/page5/documents/voterIDhajnaletal.pdf", author: "Hajnal, Lajevardi, Nielson", cat: [article, voting_rights], info: "The impact of voter ID laws on voter suppression."}
,{title: "Wall of Us", url: "https://www.wall-of-us.org/", cat: [resource, weeklies],  info: "“Four concrete acts of resistance delivered to your inbox each week.”"}
,{title: "Wallingford Indivisible", url: "https://www.facebook.com/groups/260964084339252/", cat: [organization, elections, congress], info: "Originall Wallingford Area Resistance, large group that has adopted Indivisible approach to engagement."}
,{title: "Washington Dream Coalition", url: "http://www.wadreamcoalition.org/", cat: [organization, immigration_refugees], info: "Organization for Dreamers in Washington state, education focused. Last blog post was March of 2016. I heard they are following Daniel Medina’s case."}
,{title: "Washington Immigrant Solidarity Network", url: "http://waimmigrantsolidaritynetwork.org/", cat: [organization, immigration_refugees], info: "Organization of immigrant rights groups, lawyers, labor unions, and activists to support immigrant rights in Washington state.", facebook: "WAimmigrantsolidaritynetwork"}
,{title: "Washington Post", url: "https://www.washingtonpost.com/", cat: [news], info: "I believe this national paper did the best reporting on the Trump campaign and is a good place to read about the day’s news."}
,{title: "Washington State Immigration Community Events Calendar", url: "https://www.nwirp.org/calendar-of-community-immigration-events/", cat: [calendar], info: "Know your rights presentations and the like throughout Washington state."}
,{title: "Washington Votes", url: "http://washingtonvotes.org/", cat: [resource, washington_state], info: "The best resource I have found for looking up information on bills in the Washington state legislature."}
,{title: "We have 100 days to stop Donald Trump from systemically corrupting our institutions.", url: "http://www.vox.com/policy-and-politics/2016/11/17/13626514/trump-systemic-corruption", author: "Matthew Yglesias", pub: "Vox", date: "17 Nov 2016", cat: [article, strategy]}
,{title: "We have at most a year to defend American democracy, perhaps less.", url: "http://international.sueddeutsche.de/post/157058066625/we-have-at-most-a-year-to-defend-american", author: "Matthias Kolb interviewing Timothy Snyder", pub: "SZ", date: "7 Feb 2017", info: "This interview lays out in simple and incontrovertible terms that the administration is following the same “playbook” as the Nazi Party in the 1930s.", cat: [article, civil_society], fav: true}
,{title: "Weekly Action Checklist for Democrats, Independents, and Republicans of Conscience", url: "https://jenniferhofmann.com/home/weekly-action-checklist-democrats-independents-republicans-conscience/", cat: [mailing_list, weeklies], info: "E-mail list with a weekly summary of actions to take."}
,{title: "Welcoming America", url: "https://www.welcomingamerica.org/", cat: [organization, immigration_refugees], info: "Seattle is a member of this network of “Welcoming Cities” that evolves the concept of a sanctuary city. This is what Trump wants to attack."}
,{title: "What Do I Do About Trump?", url: "http://whatdoidoabouttrump.com/", cat: [resource, strategy], info: "They pull together action items from over 30 organizations into one location. You might prefer this to dozens of emails sent to your inbox everyday."}
,{title: "What psychology teaches us about opposing an unpopular president.", url: "http://www.vox.com/the-big-idea/2017/2/2/14479726/majority-minority-politics-trump-psychology-resistance", cat: [article, strategy], author: "Robb Willer", pub: "Vox", date: "2 Feb 2017"}
,{title: "What Really Scared Me About Trump's Speech.", url: "http://www.truth-out.org/opinion/item/39694-what-really-scared-me-about-trump-s-speech", author: "Kelly Hayes", pub: "Truthout", date: "2 Mar 2017", cat: [article, trump], info: "The author argues that as Trump is being normalized, resisters to his administration operate under some delusions and misconceptions."}
,{title: "What the Fuck Just Happened Today?", url: "https://whatthefuckjusthappenedtoday.com/", cat: [news, mailing_list, trump], fav: true, info: "This is, bar none, the best daily summary of the Trump administration. If you can’t stand the news these days, this is sufficient to stay informed enough to act."}
,{title: "What to Do When You See a Swastika (or Other Hate-Based Graffiti).", url: "http://www.thestranger.com/we-saw-you/2016/12/06/24731801/what-to-do-when-you-see-a-swastika-or-other-hate-based-graffiti", author: "Ana Sofia Knauf", pub: "The Stranger", date: "6 Dec 2016", info: "Document and report it before you clean it up, here’s how and to whom.", cat: [article, civil_society]}
,{title: "WhatsApp", url: "https://www.whatsapp.com/", cat: [app, security], info: "Another encrypted messaging app. I list it here to encourage you to use Signal instead."}
,{title: "Which VPN Services Keep You Anonymous in 2017?", url: "https://torrentfreak.com/vpn-services-anonymous-review-2017-170304/", author: "Ernesto", pub: "TorrentFreak", date: "4 Mar 2017", cat: [article, privacy]}
,{title: "While Trump Was Dominating In Deep-Red Oklahoma, This Democrat Won A Landslide.", author: "Zach Carter", pub: "The Huffington Post", date: "9 Mar 2017", url: "http://www.huffingtonpost.com/entry/democratic-party-future-rural_us_58b7089ee4b019d36d0fecb4", cat: [article, elections], info: "“Joe Maxwell is urging his party not to give up on rural America.”"}
,{title: "White House Inc.", url: "https://whitehouseinc.org/", cat: [resource, trump, corruption], info: "Since Trump hasn’t divested in his businesses, this site connects you with one of his companies at random so you can talk to them about your policy concerns."}
,{title: "Who Decides? The status of women’s reproductive rights in the US", url: "http://www.prochoiceamerica.org/government-and-you/who-decides/", cat: [resource, womens_rights], author: "NARAL", info: "Summary information about reproductive rights, state-by-state."}
,{title: "Who is my representative?", url: "http://whoismyrepresentative.com/", cat: [resource, congress], info: "Enter your zip code, get contact information for your congressional representative and senator."}
,{title: "Working Families Party", url: "http://workingfamilies.org/", cat: [campaign, voting_rights], info: "This is a 3rd party that is active in the northeast of the United States. They have had some interesting electoral successes in local races."}
,{title: "Write and Be Counted: Op-Eds and Letters.", url: "http://ccmc.org/tips/write-and-be-counted-op-eds-and-letters/", cat: [resource, strategy, media], pub: "Communications Consortium Media Center", info: "Lots of help for writing letters and op-eds."}
];
//“” ’
//https://www.theguardian.com/us-news/2017/apr/03/donald-trump-immigration-deportation-protest-secret-agenda
//https://istrumpatmaralago.org/
//https://www.womensmarch.com/